image:
  repository: zanylizard/autostorm
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 31001

ingress:
  enabled: true
  className: "nginx"  # This should match your Ingress class
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []
